main/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
     path('',views.index,name='index'),
     path('menu/',views.menu,name='menu'),
     path('about/',views.about,name='about'),
     path('contact/',views.contact,name='contact'),
]

cook_room/models.py
from django.db import models

class Dish(models.Model):
    type = [
       ('pizza','Pizza'),
       ('burger','Burger'),
       ('pasta','Pasta'),
       ('drink','Drink'),
    ]
    name = models.CharField('Name',max_length=200)
    description = models.CharField('Description',max_length=200)
    small_description = models.CharField('Small description',max_length=100,blank=True)
    price = models.IntegerField(verbose_name='Price')
    dish_type = models.CharField('Type',choices=type,max_length=200)
    img = models.ImageField(verbose_name='Image',upload_to='dishs/')
    to_main_page = models.BooleanField(verbose_name='To Main Page',blank=True)
    def __str__(self):
        return self.name

class Chef(models.Model):
    chef_type = [
        ('Chef','Chef'),
        ('Su Chef','Su Chef'),
        ('Pizza Maker','Pizza Maker'),
        ('Confectioner','Confectioner'),
    ]
    name = models.CharField('Name',max_length=200)
    type = models.CharField('Type',max_length=200,choices=chef_type)
    description = models.CharField('Description',max_length=200)
    img = models.ImageField(verbose_name='Image',upload_to='chefs/')
    status = models.BooleanField(verbose_name='Status')
    def __str__(self):
        return self.name

pages/models.py
from django.db import models
from django.utils import timezone

class Contact(models.Model):
    name = models.CharField('Name',max_length=200)
    email = models.EmailField(verbose_name='Email')
    subject = models.CharField('Subject',max_length=200)
    message = models.CharField('Message',max_length=500)
    date_added = models.DateField(verbose_name='Дата создания',
                                  auto_now_add=True)
    status = models.BooleanField(verbose_name='Status',default=False)
    def __str__(self):
        return self.subject

pages/forms.py
from django import forms

class ContactForm(forms.Form):
    required_css_class = "form-control"
    name = forms.CharField(label='Name',max_length=200)
    email = forms.EmailField(label='Email')
    subject = forms.CharField(label='Subject',max_length=200)
    message = forms.CharField(label='Message',max_length=500)

cook_room/views.py
from django.shortcuts import render

pages/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect

from .forms import ContactForm
from .models import Contact
from cook_room.models import Dish,Chef

from math import ceil


def split_list(item_list):
    separator = ceil(len(item_list)/2)
    first_half = item_list[:separator]
    second_half = item_list[separator:]
    return first_half,second_half

def index(request):
    pizzas = Dish.objects.filter(dish_type='pizza',to_main_page=True)
    pizza_meals_left = pizzas[:3]
    pizza_meals_right = pizzas[3:6]
    pizza_price_left, pizza_price_right = split_list(Dish.objects.filter(dish_type='pizza'))
    pizza_tab = pizzas[:3]
    drinks = Dish.objects.filter(dish_type='drink',to_main_page=True)[:3]
    burgers = Dish.objects.filter(dish_type='burger',to_main_page=True)[:3]
    pastas = Dish.objects.filter(dish_type='pasta',to_main_page=True)[:3]
    context = {'pizzas':pizzas,
               'pizza_meals_left':pizza_meals_left,
               'pizza_meals_right':pizza_meals_right,
               'pizza_price_left':pizza_price_left,
               'pizza_price_right':pizza_price_right,
               'pizza_tab':pizza_tab,
               'drinks':drinks,
               'burgers':burgers,
               'pastas':pastas}
    return render(request,'index.html',context)

def menu(request):
    pizzas = Dish.objects.filter(dish_type='pizza',to_main_page=True)
    pizza_meals_left = pizzas[:3]
    pizza_meals_right = pizzas[3:6]
    pizza_price_left, pizza_price_right = split_list(Dish.objects.filter(dish_type='pizza'))
    burgers = Dish.objects.filter(dish_type='burger',to_main_page=True)[:3]
    drinks = Dish.objects.filter(dish_type='drink',to_main_page=True)[:3]
    pastas = Dish.objects.filter(dish_type='pasta',to_main_page=True)[:3]
    context = { 'pizzas':pizzas,
               'pizza_meals_left':pizza_meals_left,
               'pizza_meals_right':pizza_meals_right,
               'pizza_price_left':pizza_price_left,
               'pizza_price_right':pizza_price_right,
               'drinks':drinks,
               'burgers':burgers,
               'pastas':pastas}
    return render(request,'menu.html',context)

def about(request):
    chefs = Chef.objects.filter(status=True)
    context = {'chefs':chefs}
    return render(request,'about.html',context)

def contact(request):
    if request.method != 'POST':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            new_contact = Contact.objects.create(
                        name=form.cleaned_data['name'],
                        email=form.cleaned_data['email'],
                        subject=form.cleaned_data['subject'],
                        message=form.cleaned_data['message'])
            new_contact.save()
            return HttpResponseRedirect(reverse('pages:index'))
    context = {'form':form }
    return render(request,'contact.html',context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}Pizza{% endblock title %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nothing+You+Could+Do" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css'%}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css'%}">


    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
  	<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
		      <a class="navbar-brand" href="{% url 'pages:index' %}"><span class="flaticon-pizza-1 mr-1"></span>Pizza<br><small>Comfortable</small></a>
		      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
		        <span class="oi oi-menu"></span> Menu
		      </button>
	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	          <li class="nav-item active"><a href="{% url 'pages:index' %}" class="nav-link">Home</a></li>
	          <li class="nav-item"><a href="{% url 'pages:menu' %}" class="nav-link">Menu</a></li>
            <li class="nav-item"><a href="{% url 'pages:about' %}" class="nav-link">About</a></li>
	          <li class="nav-item"><a href="{% url 'pages:contact' %}" class="nav-link">Contact</a></li>
	        </ul>
	      </div>
		  </div>
	  </nav>
    <!-- Конец navbar -->
    <section class="home-slider owl-carousel img" style="background-image: url({% static 'images/bg_1.jpg'%});">
    {% block slider %}{% endblock slider %}
    </section>
  {% block content %}{% endblock content %}
    <footer class="ftco-footer ftco-section img">
      <!-- Footer Про нас -->
      <div class="overlay"></div>
      <div class="container">
        <div class="row mb-5">
          <div class="col-lg-6 col-md-6 mb-5 mb-md-5">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">About Us</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <!-- Footer Контакты -->
          <div class="col-lg-6 col-md-6 mb-5 mb-md-5">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </footer>



  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="{% static 'js/jquery.min.js'%}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js'%}"></script>
  <script src="{% static 'js/popper.min.js'%}"></script>
  <script src="{% static 'js/bootstrap.min.js'%}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js'%}"></script>
  <script src="{% static 'js/jquery.waypoints.min.js'%}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js'%}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
  <script src="{% static 'js/aos.js'%}"></script>
  <script src="{% static 'js/jquery.animateNumber.min.js'%}"></script>
  <script src="{% static 'js/bootstrap-datepicker.js'%}"></script>
  <script src="{% static 'js/jquery.timepicker.min.js'%}"></script>
  <script src="{% static 'js/scrollax.min.js'%}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static 'js/google-map.js'%}"></script>
  <script src="{% static 'js/main.js'%}"></script>

  </body>
</html>

templates/block/meals_left.html
<div class="col-lg-4 d-flex ftco-animate">
   <div class="services-wrap d-flex">
     <a href="#" class="img" style="background-image: url({{ dish.img.url }});"></a>
     <div class="text p-4">
       <h3>{{ dish.name}}</h3>
       <p>{{ dish.description }} </p>
       <p class="price"><span>${{ dish.price }}</span> <a href="{% url 'pages:contact'%}" class="ml-2 btn btn-white btn-outline-white">Order</a></p>
     </div>
   </div>
 </div>

templates/block/meals_right.html
<div class="col-lg-4 d-flex ftco-animate">
   <div class="services-wrap d-flex">
     <a href="#" class="img order-lg-last" style="background-image: url({{ dish.img.url }});"></a>
     <div class="text p-4">
       <h3>{{ dish.name}}</h3>
       <p>{{ dish.description }} </p>
       <p class="price"><span>${{ dish.price }}</span> <a href="{% url 'pages:contact'%}" class="ml-2 btn btn-white btn-outline-white">Order</a></p>
     </div>
   </div>
 </div>

templates/block/pricing.html
<div class="pricing-entry d-flex ftco-animate">
  <div class="img" style="background-image: url({{ dish.img.url }});"></div>
  <div class="desc pl-3">
    <div class="d-flex text align-items-center">
      <h3><span>{{ dish.name }}</span></h3>
      <span class="price">${{ dish.price }}</span>
    </div>
    <div class="d-block">
      <p>{{ dish.small_description }}</p>
    </div>
  </div>
</div>

templates/block/tab_block.html
<div class="col-md-4 text-center">
  <div class="menu-wrap">
    <a href="#" class="menu-img img mb-4" style="background-image: url({{ dish.img.url }});"></a>
    <div class="text">
      <h3><a href="#">{{ dish.name }}</a></h3>
      <p>{{ dish.small_description }}</p>
      <p class="price"><span>${{ dish.price }}</span></p>
      <p><a href="{% url 'pages:contact'%}" class="btn btn-white btn-outline-white">Order</a></p>
    </div>
  </div>
</div>

templates/contact.html
{% extends 'base.html'%}
{% load static %}
{% block title %}Contact{% endblock title %}

{% block slider %}
<div class="slider-item" style="background-image: url({% static 'images/contact-slider.jpg'%});">
  <div class="overlay"></div>
  <div class="container">
    <div class="row slider-text justify-content-center align-items-center">

      <div class="col-md-7 col-sm-12 text-center ftco-animate">
        <h1 class="mb-3 mt-5 bread">Contact Us</h1>
        <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Contact</span></p>
      </div>

    </div>
  </div>
</div>
{% endblock slider %}

{% block content %}
<section class="ftco-section contact-section">
  <div class="container mt-5">
    <div class="row block-9">
      <div class="col-md-4 contact-info ftco-animate">
        <div class="row">
          <div class="col-md-12 mb-4">
            <h2 class="h4">Contact Information</h2>
          </div>
          <div class="col-md-12 mb-3">
            <p><span>Address:</span> 198 West 21th Street, Suite 721 New York NY 10016</p>
          </div>
          <div class="col-md-12 mb-3">
            <p><span>Phone:</span> <a href="tel://1234567920">+ 1235 2355 98</a></p>
          </div>
          <div class="col-md-12 mb-3">
            <p><span>Email:</span> <a href="mailto:info@yoursite.com">info@yoursite.com</a></p>
          </div>
          <div class="col-md-12 mb-3">
            <p><span>Website:</span> <a href="#">yoursite.com</a></p>
          </div>
        </div>
      </div>
      <div class="col-md-1"></div>
      <div class="col-md-6 ftco-animate">
        <form action="{% url 'pages:contact' %}" class="contact-form" method="post">
          {% csrf_token %}
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <input type="text" name="name" maxlength="200" required="" id="id_name" class="form-control" placeholder="Your Name">
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <input type="email" name="email" required="" id="id_email" class="form-control" placeholder="Email">
              </div>
              </div>
          </div>
          <div class="form-group">
            <input type="text" name="subject" maxlength="200" required="" id="id_subject" class="form-control" placeholder="Subject">
          </div>
          <div class="form-group">
            <input type="text" name="message" maxlength="500" required="" id="id_message" class="form-control" placeholder="Message">
          </div>
          <div class="form-group">
            <button name="submit" class="btn btn-primary py-3 px-5">Send Message</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/example.html
{% extends 'base.html'%}
{% load static %}
{% block title %}Главная{% endblock title %}

{% block slider %}
{% endblock slider %}

{% block content %}
{% endblock content %}

templates/index.html
{% extends 'base.html'%}
{% load static %}
{% block title %}Главная{% endblock title %}

<!-- Начало слайдера на главной странице -->
{% block slider %}
  <div class="slider-item">
    <div class="overlay"></div>
    <div class="container">
      <div class="row slider-text align-items-center" data-scrollax-parent="true">

        <div class="col-md-6 col-sm-12 ftco-animate">
          <span class="subheading">Delicious</span>
          <h1 class="mb-4">Italian Cuizine</h1>
          <p class="mb-4 mb-md-5">A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
          <p><a href="{% url 'pages:contact' %}" class="btn btn-primary p-3 px-xl-4 py-xl-3">Contact Us</a> <a href="{% url 'pages:menu' %}" class="btn btn-white btn-outline-white p-3 px-xl-4 py-xl-3">View Menu</a></p>
        </div>
        <div class="col-md-6 ftco-animate">
          <img src="{% static 'images/sl_1.png'%}" class="img-fluid" alt="">
        </div>
      </div>
    </div>
  </div>

  <div class="slider-item">
    <div class="overlay"></div>
    <div class="container">
      <div class="row slider-text align-items-center" data-scrollax-parent="true">

        <div class="col-md-6 col-sm-12 order-md-last ftco-animate">
          <span class="subheading">Crunchy</span>
          <h1 class="mb-4">Italian Pizza</h1>
          <p class="mb-4 mb-md-5">A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
          <p><a href="{% url 'pages:contact' %}" class="btn btn-primary p-3 px-xl-4 py-xl-3">Contact Us</a> <a href="{% url 'pages:menu' %}" class="btn btn-white btn-outline-white p-3 px-xl-4 py-xl-3">View Menu</a></p>
        </div>
        <div class="col-md-6 ftco-animate">
          <img src="{% static 'images/sl_2.png'%}" class="img-fluid" alt="">
        </div>

      </div>
    </div>
  </div>

  <div class="slider-item" style="background-image: url({% static 'images/bg_3.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
      <div class="row slider-text justify-content-center align-items-center" data-scrollax-parent="true">

        <div class="col-md-7 col-sm-12 text-center ftco-animate">
          <span class="subheading">Welcome</span>
          <h1 class="mb-4">We cooked your desired Pizza Recipe</h1>
          <p class="mb-4 mb-md-5">A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
          <p><a href="{% url 'pages:contact' %}" class="btn btn-primary p-3 px-xl-4 py-xl-3">Contact Us</a> <a href="{% url 'pages:menu' %}" class="btn btn-white btn-outline-white p-3 px-xl-4 py-xl-3">View Menu</a></p>
        </div>

      </div>
    </div>
  </div>
{% endblock slider %}
  <!-- Конец слайдера -->
  {% block content %}
  <!-- Ползунок с контактными данными -->
  <section class="ftco-intro">
    <div class="container-wrap">
      <div class="wrap d-md-flex">
        <div class="info">
          <div class="row no-gutters">
            <div class="col-md-4 d-flex ftco-animate">
              <div class="icon"><span class="icon-phone"></span></div>
              <div class="text">
                <h3>000 (123) 456 7890</h3>
                <p>A small river named Duden flows</p>
              </div>
            </div>
            <div class="col-md-4 d-flex ftco-animate">
              <div class="icon"><span class="icon-my_location"></span></div>
              <div class="text">
                <h3>198 West 21th Street</h3>
                <p>Suite 721 New York NY 10016</p>
              </div>
            </div>
            <div class="col-md-4 d-flex ftco-animate">
              <div class="icon"><span class="icon-clock-o"></span></div>
              <div class="text">
                <h3>Open Monday-Friday</h3>
                <p>8:00am - 9:00pm</p>
              </div>
            </div>
          </div>
        </div>
        <div class="social d-md-flex pl-md-5 p-4 align-items-center">
          <ul class="social-icon">
            <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
            <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
            <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
          </ul>
        </div>
      </div>
    </div>
  </section>
  <!-- Конец ползунка -->
  <!-- Блок Welcome -->
  <section class="ftco-about d-md-flex">
    <div class="one-half img" style="background-image: url({% static 'images/about.jpg' %});"></div>
    <div class="one-half ftco-animate">
      <div class="heading-section ftco-animate ">
        <h2 class="mb-4">Welcome to <span class="flaticon-pizza">Pizza</span> A Restaurant</h2>
      </div>
      <div>
        <p>On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from its origin would be the word "and" and the Little Blind Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until a few insidious Copy Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where they abused her for their.</p>
      </div>
    </div>
  </section>
  <!-- Конец Welcome -->
  <!-- Блок Our Services -->
  <section class="ftco-section ftco-services">
    <div class="overlay"></div>
    <div class="container">
      <div class="row justify-content-center mb-5 pb-3">
        <div class="col-md-7 heading-section ftco-animate text-center">
          <h2 class="mb-4">Our Services</h2>
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 ftco-animate">
          <div class="media d-block text-center block-6 services">
            <div class="icon d-flex justify-content-center align-items-center mb-5">
              <span class="flaticon-diet"></span>
            </div>
            <div class="media-body">
              <h3 class="heading">Healthy Foods</h3>
              <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>
            </div>
          </div>
        </div>
        <div class="col-md-4 ftco-animate">
          <div class="media d-block text-center block-6 services">
            <div class="icon d-flex justify-content-center align-items-center mb-5">
              <span class="flaticon-bicycle"></span>
            </div>
            <div class="media-body">
              <h3 class="heading">Fastest Delivery</h3>
              <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>
            </div>
          </div>
        </div>
        <div class="col-md-4 ftco-animate">
          <div class="media d-block text-center block-6 services">
            <div class="icon d-flex justify-content-center align-items-center mb-5"><span class="flaticon-pizza-1"></span></div>
            <div class="media-body">
              <h3 class="heading">Original Recipes</h3>
              <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Конец Our Services -->
  <!-- Секция Hot pizza Meals -->
 <section class="ftco-section">
   <div class="container">
     <div class="row justify-content-center mb-5 pb-3">
       <div class="col-md-7 heading-section ftco-animate text-center">
         <h2 class="mb-4">Hot Pizza Meals</h2>
         <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
       </div>
     </div>
   </div>
   <div class="container-wrap">
     <div class="row no-gutters d-flex">
     {% for dish in pizza_meals_left %}
      {% include 'block/meals_left.html'%}
       {% endfor %}

       {% for dish in pizza_meals_right %}
       {% include 'block/meals_right.html' %}
       {% endfor %}


   <div class="container">
     <div class="row justify-content-center mb-5 pb-3 mt-5 pt-5">
       <div class="col-md-7 heading-section text-center ftco-animate">
         <h2 class="mb-4">Our Menu Pricing</h2>
         <p class="flip"><span class="deg1"></span><span class="deg2"></span><span class="deg3"></span></p>
         <p class="mt-5">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
       </div>
     </div>

     <div class="row">

       <div class="col-md-6">
         {% for dish in pizza_price_left %}
         {% include 'block/pricing.html'%}
         {% endfor %}
        </div>



       <div class="col-md-6">
         {% for dish in pizza_price_right %}
         {% include 'block/pricing.html' %}
         {% endfor %}
       </div>
     </div>
   </div>
 </section>
 <!-- Конец Hot pizza Meals -->
 <!-- Секция Menu -->
 <section class="ftco-menu">
   <div class="container-fluid">
     <div class="row d-md-flex">
       <div class="col-lg-4 ftco-animate img f-menu-img mb-5 mb-md-0" style="background-image: url({% static 'images/menu-static-left.jpg' %});">
       </div>

       <div class="col-lg-8 ftco-animate p-md-5">
         <div class="row">

           <div class="col-md-12 nav-link-wrap mb-5">
             <div class="nav ftco-animate nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
               <a class="nav-link active" id="v-pills-1-tab" data-toggle="pill" href="#v-pills-1" role="tab" aria-controls="v-pills-1" aria-selected="true">Pizza</a>

               <a class="nav-link" id="v-pills-2-tab" data-toggle="pill" href="#v-pills-2" role="tab" aria-controls="v-pills-2" aria-selected="false">Drinks</a>

               <a class="nav-link" id="v-pills-3-tab" data-toggle="pill" href="#v-pills-3" role="tab" aria-controls="v-pills-3" aria-selected="false">Burgers</a>

               <a class="nav-link" id="v-pills-4-tab" data-toggle="pill" href="#v-pills-4" role="tab" aria-controls="v-pills-4" aria-selected="false">Pasta</a>
             </div>
           </div>

           <div class="col-md-12 d-flex align-items-center">

             <div class="tab-content ftco-animate" id="v-pills-tabContent">

               <div class="tab-pane fade show active" id="v-pills-1" role="tabpanel" aria-labelledby="v-pills-1-tab">
                 <div class="row">
                   {% for dish in pizza_tab %}
                   {% include 'block/tab_block.html'%}
                   {% endfor %}
                  </div>
                </div>

               <div class="tab-pane fade" id="v-pills-2" role="tabpanel" aria-labelledby="v-pills-2-tab">
                 <div class="row">
                   {% for dish in drinks %}
                   {% include 'block/tab_block.html'%}
                   {% endfor %}
                 </div>
               </div>

               <div class="tab-pane fade" id="v-pills-3" role="tabpanel" aria-labelledby="v-pills-3-tab">
                 <div class="row">
                   {% for dish in burgers%}
                   {% include 'block/tab_block.html'%}
                   {% endfor %}
                 </div>
               </div>

               <div class="tab-pane fade" id="v-pills-4" role="tabpanel" aria-labelledby="v-pills-4-tab">
                 <div class="row">
                   {% for dish in pastas %}
                   {% include 'block/tab_block.html'%}
                   {% endfor %}
                 </div>
               </div>

             </div>
           </div>
         </div>
       </div>
     </div>
   </div>
 </section>
 <!-- Конец Menu -->
{% endblock content %}